services:
  - type: web
    name: marcostv
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread --threads 8 -b 0.0.0.0:$PORT universaltv:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
